---
apiVersion: v1
kind: Service
metadata:
  name: uaa-service
  labels:
    app: uaa-deployment
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http-uaa
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
  selector:
    app: uaa-deployment
